package com.code.model;

import com.code.model.base.BaseConfigRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ConfigRecord extends BaseConfigRecord<ConfigRecord> {
	public static final ConfigRecord dao = new ConfigRecord().dao();
}
