package com.code.model;

import com.code.model.base.BaseConfig;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Config extends BaseConfig<Config> {
	public static final Config dao = new Config().dao();
}
