package com.code.model;

import com.code.model.base.BaseConfigKeyVal;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ConfigKeyVal extends BaseConfigKeyVal<ConfigKeyVal> {
	public static final ConfigKeyVal dao = new ConfigKeyVal().dao();
}
