package com.code.model;

import com.code.model.base.BaseTemplate;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Template extends BaseTemplate<Template> {
	public static final Template dao = new Template().dao();
}
