package com.code.model;

import com.code.model.base.BaseJdbcConfig;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class JdbcConfig extends BaseJdbcConfig<JdbcConfig> {
	public static final JdbcConfig dao = new JdbcConfig().dao();
}
