package com.code.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseConfig<M extends BaseConfig<M>> extends Model<M> implements IBean {

	public M setConfigId(java.lang.Integer configId) {
		set("config_id", configId);
		return (M)this;
	}
	
	public java.lang.Integer getConfigId() {
		return getInt("config_id");
	}

	public M setConfigName(java.lang.String configName) {
		set("config_name", configName);
		return (M)this;
	}
	
	public java.lang.String getConfigName() {
		return getStr("config_name");
	}

	public M setInputType(java.lang.String inputType) {
		set("input_type", inputType);
		return (M)this;
	}
	
	public java.lang.String getInputType() {
		return getStr("input_type");
	}

	public M setProjectId(java.lang.Integer projectId) {
		set("project_id", projectId);
		return (M)this;
	}
	
	public java.lang.Integer getProjectId() {
		return getInt("project_id");
	}

}
