package com.code.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseConfigRecord<M extends BaseConfigRecord<M>> extends Model<M> implements IBean {

	public M setConfigRecordId(java.lang.Integer configRecordId) {
		set("config_record_id", configRecordId);
		return (M)this;
	}
	
	public java.lang.Integer getConfigRecordId() {
		return getInt("config_record_id");
	}

	public M setConfigId(java.lang.Integer configId) {
		set("config_id", configId);
		return (M)this;
	}
	
	public java.lang.Integer getConfigId() {
		return getInt("config_id");
	}

	public M setTemplateId(java.lang.Integer templateId) {
		set("template_id", templateId);
		return (M)this;
	}
	
	public java.lang.Integer getTemplateId() {
		return getInt("template_id");
	}

	public M setProjectId(java.lang.Integer projectId) {
		set("project_id", projectId);
		return (M)this;
	}
	
	public java.lang.Integer getProjectId() {
		return getInt("project_id");
	}

}
